require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - 'lib/exceptions.rb'
